### ISSUE TITLE
เวลา login ของ admin add ลง database ไม่ตรงเวลาจริงครับ

### ISSUE THREAD

**Issue by pgpong** [ALTELMA/office-supply-storage-ci3#1]

**Comment by pgpong** [comment]
![time](https://cloud.githubusercontent.com/assets/19702279/15735039/80c9126a-28bf-11e6-9348-783853cc0414.png)

**Comment by ALTELMA** [comment]
สามารถแก้ไขได้ที่ php.ini ครับ ถ้าไม่อยากแก้ที่ php.ini
สามารถแก้ไขได้ โดยการเพิ่ม date_default_timezone_set('Asia/Bangkok');
ที่ไฟล์ index.php ครับ

ขออภัยนะครับที่ตอบช้า ขอบคุณมากครับสำหรับ feedback ดีๆ :dancers:
