### ISSUE TITLE
ปัญหา Not Found The requested URL was not found on this server.

### ISSUE THREAD

**Issue by quality-of-life** [ALTELMA/office-supply-storage-ci3#4]
ภาพ : 
![Error](https://user-images.githubusercontent.com/57080398/67649010-f4798e00-f969-11e9-85fe-1298aabec99d.JPG)

หลังจากล็อกอินเข้าไปแล้วก็เป็นตามภาพเลยครับ มันไม่เจอลิ้งค์ ตามที่ระบุไว้ใน class user extends MY_Controller ตรง function verifylogin ผมเข้าใจถูกต้องไหมครับ ช่วยบอกวิธีแก้ให้หน่อยครับ

"Not Found
The requested URL was not found on this server."

**Comment by ALTELMA** [comment]
@quality-of-life รัน Web Server ด้วยอะไรครับ? ขอโทษที่ตอบช้านะครับ

**Comment by ALTELMA** [comment]
ขออนุญาตปิด issue นะครับ
